[mongodb]
mongodb.medaknaresh.digital

[catalogue]
catalogue.medaknaresh.digital

[redis]
redis.medaknaresh.digital

[user]
user.medaknaresh.digital

[cart]
cart.medaknaresh.digital 

[frontend]
172.31.5.66



